# Generated by Django 6.0.6 on 2026-07-06 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('device_verification', 'Device Verification')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSessionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('UNAUTHENTICATED', 'Unauthenticated'), ('DEVICE_VERIFIED', 'Device Verified'), ('GEOFENCE_PASSED', 'Geofence Passed'), ('FINGERPRINT_REQUIRED', 'Fingerprint Required'), ('FINGERPRINT_FAILED', 'Fingerprint Failed'), ('OTP_REQUIRED', 'OTP Required'), ('ATTENDANCE_GRANTED', 'Attendance Granted')], default='UNAUTHENTICATED', max_length=50)),
                ('device_verified', models.BooleanField(default=False)),
                ('geofence_verified', models.BooleanField(default=False)),
                ('fingerprint_verified', models.BooleanField(default=False)),
                ('otp_verified', models.BooleanField(default=False)),
                ('fingerprint_attempts', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
