# Generated by Django 6.0.6 on 2026-07-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersessionstate',
            name='current_state',
            field=models.CharField(choices=[('UNAUTHENTICATED', 'Unauthenticated'), ('DEVICE_VERIFIED', 'Device Verified'), ('GEOFENCE_PASSED', 'Geofence Passed'), ('FINGERPRINT_REQUIRED', 'Fingerprint Required'), ('FINGERPRINT_FAILED', 'Fingerprint Failed'), ('OTP_REQUIRED', 'OTP Required'), ('ATTENDANCE_GRANTED', 'Attendance Granted'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out')], default='UNAUTHENTICATED', max_length=50),
        ),
    ]
