# Generated by Django 6.0.6 on 2026-06-28 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSessionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('UNAUTHENTICATED', 'Unauthenticated'), ('DEVICE_VERIFIED', 'Device Verified'), ('GEOFENCE_PASSED', 'Geofence Passed'), ('FINGERPRINT_REQUIRED', 'Fingerprint Required'), ('FINGERPRINT_FAILED', 'Fingerprint Failed'), ('OTP_FALLBACK', 'OTP Fallback'), ('ATTENDANCE_GRANTED', 'Attendance Granted')], default='UNAUTHENTICATED', max_length=50)),
                ('device_verified', models.BooleanField(default=False)),
                ('geofence_verified', models.BooleanField(default=False)),
                ('fingerprint_fail_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
