# Generated by Django 6.0.6 on 2026-06-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersessionstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersessionstate',
            old_name='fingerprint_fail_count',
            new_name='fingerprint_attempts',
        ),
        migrations.AddField(
            model_name='usersessionstate',
            name='fingerprint_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersessionstate',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersessionstate',
            name='current_state',
            field=models.CharField(choices=[('UNAUTHENTICATED', 'Unauthenticated'), ('DEVICE_VERIFIED', 'Device Verified'), ('GEOFENCE_PASSED', 'Geofence Passed'), ('FINGERPRINT_REQUIRED', 'Fingerprint Required'), ('FINGERPRINT_FAILED', 'Fingerprint Failed'), ('OTP_REQUIRED', 'OTP Required'), ('ATTENDANCE_GRANTED', 'Attendance Granted')], default='UNAUTHENTICATED', max_length=50),
        ),
    ]
