# Generated by Django 6.0.6 on 2026-07-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_classroom_blebeacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='radius_meters',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_number',
            field=models.CharField(max_length=50),
        ),
    ]
