# Generated by Django 6.0.6 on 2026-07-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_classroom_latitude_classroom_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
