# Generated by Django 6.0.6 on 2026-07-11 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementlog',
            name='beacon_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movementlog',
            name='wifi_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_logs', to='attendance.attendancesession'),
        ),
        migrations.AlterField(
            model_name='movementlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movement_logs', to='students.student'),
        ),
    ]
