# Generated by Django 6.0.6 on 2026-07-12 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_movementlog_beacon_valid_movementlog_wifi_valid_and_more'),
        ('courses', '0002_classroom_blebeacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.classroom'),
        ),
    ]
