# Generated by Django 6.0.6 on 2026-07-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancesession_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='auto_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
