# Generated by Django 6.0.6 on 2026-07-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancesession_auto_closed_and_more'),
        ('courses', '0002_classroom_blebeacon'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.timetable'),
        ),
    ]
