# Generated by Django 6.0.6 on 2026-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancesession_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='is_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='override_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
