# Generated by Django 6.0.6 on 2026-07-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancesession_is_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='checkout_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
