# Generated by Django 6.0.6 on 2026-07-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendancesession_checkout_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='override_duration_minutes',
            field=models.IntegerField(default=120, help_text='Duration for postponed/replacement classes in minutes'),
        ),
    ]
